spring:
  datasource:
    url: jdbc:mysql://xxx:3306/xxx?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username:
    password:
    driverClassName: com.mysql.jdbc.Driver

databaseName: # 数据库名称
filePath: # 生成路径